PORNEW/POR/Models/FixedAllowanceDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAllowanceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedAllowanceDetail()
        {
            this.FixedAllowanceCancels = new HashSet<FixedAllowanceCancel>();
        }
    
        public int FADID { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<int> AllowanceCategoryID { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<int> FullHalfPay { get; set; }
        public string Sno { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CampAuthority { get; set; }
        public Nullable<System.DateTime> CampAuthorityDate { get; set; }
        public string CancelReferanceNo { get; set; }
        public Nullable<int> CeasedId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public string EstablishmentId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> AllowanceTypeId { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
    
        public virtual Allowance Allowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedAllowanceCancel> FixedAllowanceCancels { get; set; }
    }
}

PORNEW/POR/Models/_FixedAllowanceDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace POR.Models
{
    public class _FixedAllowanceDetail
    {
        [Key]
        public int FADID { get; set; }

        [Required(ErrorMessage = "The value 'SELECT' is not valid for Service Category.")]        
        public Nullable<int> ServiceCategoryId { get; set; }
        public string RankName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> RankId { get; set; }
        [Required(ErrorMessage = "The value 'SELECT' is not valid for Allowance Category.")]
        public Nullable<int> AllowanceCategoryID { get; set; }
        [Required(ErrorMessage = "The value 'SELECT' is not valid for Payment Type.")]
        public Nullable<int> FullHalfPay { get; set; }         
        public Nullable<int> ServiceType { get; set; }

        [Required(ErrorMessage = "The value 'SELECT' is not valid for Allowance.")]
        public Nullable<int> AllowanceId { get; set; }         
        public string Sno { get; set; }

        [Required(ErrorMessage = "Effective Date cann't Null")]
        public Nullable<System.DateTime> EffectiveDate { get; set; }        
        public Nullable<System.DateTime> EndDate { get; set; }
        [Required(ErrorMessage = "Authority cann't Null")]
        public string CampAuthority { get; set; }
        [Required(ErrorMessage = "Authority Date cann't Null")]
        public Nullable<System.DateTime> CampAuthorityDate { get; set; }
        public string Remark { get; set; }
        [Required(ErrorMessage = "Service No cann't Null")]
        public string ServiceNo_ { get; set; }

        public string LocationId { get; set; }

        public int ATID { get; set; }
        public string AllowanceDescreption { get; set; }
        public Nullable<int> Status { get; set; }
    }
}

PORNEW/POR/Controllers/FixedAllowanceDetailController.cs
using POR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using System.Transactions;
using System.Data;
using ReportData.DAL;
using System.Net;
using System.Data.Entity;


namespace POR.Controllers
{

    public class FixedAllowanceDetailController : Controller
    {
        dbContext _db = new dbContext();
        dbContextCommonData _dbCommonData = new dbContextCommonData();
        int? UID = 0;
        DateTime? FromDate_ = new DateTime();
        DateTime? ToDate_ = new DateTime();
        //
        // GET: /FixedAllowanceDetail/
        //RSID = RecordStatusId ,check Record Status ex:Forward or Reject
        [HttpGet]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? RSID)
        {
            int? UID = Convert.ToInt32(Session["UID"]);
            int pageSize = 0;
            int pageNumber = 1;

            if (UID != 0)
            {
                var UserInfo = _db.UserInfoes.Where(x => x.UID == UID).FirstOrDefault();

                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "FADID" : "";
                ViewBag.DateSortParm = sortOrder == "ServiceNo" ? "Rank" : "EffectiveDate";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                //change ----var LocationId = _db.UserPermissions.Where(x => x.UserId == UID).Select(x => x.AccessLocationId).FirstOrDefault();
                var LocationId = _db.UserPermissions.Where(x => x.UserId == UID).Select(x => x.AccessLocationId).FirstOrDefault();

                List<Vw_FixedAllowanceDetail> objFixedAllowanceDetail = new List<Vw_FixedAllowanceDetail>();

                //foreach (var item in LocationId)
                //{
                //objFixedAllowanceDetail = from s in _db.Vw_FixedAllowanceDetail select s; 
                //objFixedAllowanceDetail = _db.Vw_FixedAllowanceDetail.Where(x => x.EstablishmentId == LocationId).ToList();
                //objFixedAllowanceDetail = _db.Vw_FixedAllowanceDetail.Where(x => x.RecordStatusId != 3000).Take(500).ToList();

                if (UserInfo.RoleId == 1)
                {
                    objFixedAllowanceDetail = _db.Vw_FixedAllowanceDetail.Where(x => x.EstablishmentId == LocationId && x.CreatedBy == UID && ((x.FMSID == null || x.RecordStatusId == 1000))).Take(500).ToList();
                }
                else if (UserInfo.RoleId <= 4 && UserInfo.RoleId != 1)
                {
                    objFixedAllowanceDetail = _db.Vw_FixedAllowanceDetail.Where(x => x.EstablishmentId == LocationId && ((x.CurrentStatus == UserInfo.RoleId && x.RecordStatusId == 2000 && x.IsProcessed != 1) || (x.RecordStatusId == 3000 && x.CurrentStatus == UserInfo.RoleId))).ToList();
                }

                else if (UserInfo.RoleId >= 5 && UserInfo.RoleId != 1)
                {

                    objFixedAllowanceDetail = _db.Vw_FixedAllowanceDetail.Where(x => (x.CurrentStatus == UserInfo.RoleId && x.RecordStatusId == 2000 && x.IsProcessed != 1)).Take(500).ToList();
                }

                if (!String.IsNullOrEmpty(searchString))
                {
                    objFixedAllowanceDetail = objFixedAllowanceDetail.Where(s => s.ServiceNo.Contains(searchString) || s.Rank.Contains(searchString) || s.CampAuthority.Contains(searchString)).Take(500).ToList();
                }

                switch (sortOrder)
                {
                    case "ServiceNo":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.ServiceNo).ToList();
                        break;
                    case "ServiceType":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.ServiceType).ToList();
                        break;
                    case "Rank":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.RankID).ToList();
                        break;
                    case "Name":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.Name).ToList();
                        break;
                    case "AllowanceName":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.AllowanceName).ToList();
                        break;
                    case "EffectiveDate":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderBy(s => s.EffectiveDate).ToList();
                        break;
                    case "EndDate":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderByDescending(s => s.EndDate).ToList();
                        break;
                    case "CampAuthority":
                        objFixedAllowanceDetail = objFixedAllowanceDetail.OrderByDescending(s => s.CampAuthority).ToList();
                        break;
                }

                pageSize = 10;
                pageNumber = (page ?? 1);
                return View(objFixedAllowanceDetail.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }
        [HttpGet]
        public ActionResult Index_AllRecord(string sortOrder, string currentFilter, string searchString, string LocationId, int? page, int? RSID)
        {
            int? UID = Convert.ToInt32(Session["UID"]);

            // var LocationId = _db.UserPermissions.Where(x => x.UserId == UID).Select(x => x.AccessLocationId).ToList();
            ViewBag.DDL_LocationId = new SelectList(_db.UserPermissions.Where(x => x.UserId == UID), "AccessLocationId", "AccessLocationId");

            if (UID != 0)
            {

                var UserInfo = _db.UserInfoes.Where(x => x.UID == UID).FirstOrDefault();
                string location = UserInfo.LocationId;

                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
                ViewBag.DateSortParm = sortOrder == "AllowanceName" ? "Rank" : "EffectiveDate";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                //38746
                var objVw_FixedAllowance_FLowStatus = _db.Vw_FixedAllowance_FLowStatus.ToList();


                ViewBag.CurrentFilter = searchString;
                //string LocationId_ = "CBO";
                var objFixedAllowanceDetail = from s in _db.Vw_FixedAllowance_FLowStatus
                                              where (s.FADS_CreatedBy == UID)
                                              select s;

                if (UserInfo.RoleId == 1)
                {
                    if (RSID == 3000)
                    {
                        //38746
                        objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.EstablishmentId == location && x.FADS_CreatedBy == UID && x.RecordStatusId == RSID).ToList();
                        // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.Active == 0 && x.CreatedBy == UID && x.RecordStatusId == 1000);      
                    }
                    else
                    {
                        //38746
                        objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.EstablishmentId == location && x.FADS_CreatedBy == UID).ToList();
                        // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.CreatedBy == UID && x.RecordStatusId == RSID);  
                    }
                }
                else if (UserInfo.RoleId == 6)
                {
                    objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.FADS_CreatedBy == UID).ToList();
                    // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.RecordStatusId == RSID && x.CreatedBy == UID);  
                }
                else if (UserInfo.RoleId == 7)
                {
                    objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.FADS_CreatedBy == UID).ToList();
                    // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.RecordStatusId == RSID && x.CreatedBy == UID);  
                }
                else if (UserInfo.RoleId == 5)
                {
                    //38746
                    objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.FADS_CreatedBy == UID).ToList();
                    //  objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.RecordStatusId == RSID);  
                }
                else if (UserInfo.RoleId == 8)
                {
                    objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.FADS_CreatedBy == UID).ToList();
                    // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.RecordStatusId == RSID && x.CreatedBy == UID);  
                }
                else if (UserInfo.RoleId == 3)
                {
                    if (RSID == 3000)
                    {
                        //38746
                        objVw_FixedAllowance_FLowStatus = objVw_FixedAllowance_FLowStatus.Where(x => x.EstablishmentId == location && x.FADS_CreatedBy == UID).ToList();
                        // objFixedAllowanceDetail = objFixedAllowanceDetail.Where(x => x.Active == 0 && x.CreatedBy == UID && x.RecordStatusId == 1000);      
                    }
                    else
                    {

PORNEW/POR/Views/FixedAllowanceDetail/DetailCeased.cshtml
@using POR.Models
@model POR.Models.Vw_FixedAllowanceDetail

@{
    ViewBag.Title = "DetailCeased";
}
<script src="~/Scripts/Jq.js"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<div class="content-wrapper" style="height:900px !important;">
    <section class="content-header">
        <h1>
            Fixed Allowances Details
            <small>View & Forwad to Next Authority</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
        <div id="ErrorMessage">
            @if (TempData["ScfMsg"] != null)
            {
                <div id="Msg" class="col-lg-12  alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert! </strong> @TempData["ScfMsg"]
                </div>
            }
            else if (TempData["ErrMsg"] != null)
            {
                <div id="Msg" class="col-lg-12 alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert! </strong>@TempData["ErrMsg"]
                </div>

            }
        </div>
    </section>
    <br />
    <section class="col-lg-12 nav-tabs-custom connectedSortable">
        <div class="col-lg-6">
            <br />
            <dl class="dl-horizontal">

                <dt class="form-group">
                    Service No
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ServiceNo)
                </dd>

                <dt class="form-group">
                    Service Type
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Service_Type)
                </dd>

                <dt class="form-group">
                    Rank
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Rank)
                </dd>

                <dt class="form-group">
                    Name with Initials
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt class="form-group">
                    Allowance
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AllowanceName)
                </dd>
                <dt class="form-group">
                    Allowance Category
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt class="form-group">
                    Payment Type
                </dt>

                <dd>
                    @{
                        int? PaymentTypeId = Convert.ToInt32(Model.FullHalfPay);
                        string PaymentTypeName = null;
                        if (PaymentTypeId == 1)
                        {
                            PaymentTypeName = "Half Pay";
                        }
                        else if (PaymentTypeId == 2)
                        {
                            PaymentTypeName = "Full Pay";
                        }
                        else if (PaymentTypeId == 0)
                        {
                            PaymentTypeName = "N/A";
                        }
                    }
                    @PaymentTypeName
                </dd>
                <dt class="form-group">
                    Effective Date
                </dt>

                <dd>
                    @Html.ValueFor(model => model.EffectiveDate, "{0:dd/MM/yyyy}")
                </dd>

                <dt class="form-group">
                    End Date
                </dt>

                <dd>
                    @Html.ValueFor(model => model.EndDate, "{0:dd/MM/yyyy}")
                </dd>

                <dt class="form-group">
                    Authority
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CampAuthority)
                </dd>

                <dt class="form-group">
                    Authority Date
                </dt>

                <dd>
                    @Html.ValueFor(model => model.CampAuthorityDate, "{0:dd/MM/yyyy}")

                </dd>
                <dt class="form-group">
                    Remark
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Remark)
                </dd>
            </dl>
        </div>

        <div class="col-lg-6" style="padding-top: 100px; padding-bottom: 270px; font-size: 20px; ">

            @{
                string UserRole;
                string Rdate;
                if (TempData["RejectUserRole"] != null && TempData["RejectDate"] != null)
                {
                    UserRole = TempData["RejectUserRole"].ToString();
                    Rdate = TempData["RejectDate"].ToString();
                    <div class="alert alert-error">
                        <span>@UserRole Rejected</span> <br />
                        <span>Date : @Rdate</span><br />
                        <span>Comment : @Html.DisplayFor(model => model.Comment)</span>
                    </div>
                }
            }
        </div>
    </section>

    <section>

        @{
            int? URID = Convert.ToInt32(TempData["UserRoleId"]);
            int? CurrentStatus = Convert.ToInt32(TempData["CurrentStatus"]);
            int? SubmitStatus = Convert.ToInt32(TempData["SubmitStatus"]);

            if (Model.RecordStatusId == 1000 || Model.RecordStatusId == 2000 || Model.RecordStatusId == 3000)
            {
                <div class="col-lg-12">
                    @Html.ActionLink("Back to List", "IndexCeased", "FixedAllowanceDetail", new { id = Model.FADID }, new { @class = "btn btn-info" })
                    <input id="btnCeased" type="button" value="Ceased" data-assigned-id="1000" data-toggle="modal" data-target="#exampleModalLong" class="btn btn-warning" />
                </div>
            }
            else
            {
                <div class="col-lg-12">
                    @Html.ActionLink("Back to List", "IndexCeased", "FixedAllowanceDetail", new { id = Model.FADID }, new { @class = "btn btn-info" })
                </div>
                        }
                    }

        
        
        @*Fixed Details Id popup Box value*@
        <input type="hidden" id="hndFADID" value="@Html.DisplayFor(model => model.FADID)" />
        <input type="hidden" id="hndFMSID" value="@Html.DisplayFor(model => model.FMSID)" />

    </section>

    <section class="col-lg-12 connectedSortable">
        <br />
        <ol class="breadcrumb">
            @{ dbContext _db = new dbContext(); }

            @if (ViewData["AllFlowStatus"] != null)
            {
                int? CurrentStatus_UserRole;
                string User;
                int? LogingUserRoleId = Convert.ToInt32(TempData["UserRoleId"]);

                if (TempData["CurrentStatusUserRole"] != null)
                {
                    CurrentStatus_UserRole = Convert.ToInt32(TempData["CurrentStatusUserRole"]);
                }
                else
                {
                    CurrentStatus_UserRole = null;
                }


                foreach (var DDR_1 in ViewData["UserFlow_ToolTip"] as IList<Vw_FlowStatusUser_ToolTip>)
                {

                    User = DDR_1.ServiceNo + " - " + DDR_1.Rank + " " + DDR_1.Name;

                    if (CurrentStatus_UserRole == DDR_1.RID)
                    {
                        <li class="active text-bold"> <a class="text-danger" href="#" title="">@DDR_1.RoleName</a></li>
                    }
                    else
                    {
                        <li class="active"> <a href="#" title="@User">@DDR_1.RoleName</a></li>
                    }
                }

            }
            <li class="active"><a class="details" href="javascript:;" id="details">...Flow History</a></li>
        </ol>
    </section>
</div>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="border-bottom:none !important;">
               
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @*<hr style="margin-top: 0px !important; margin-bottom: 0px !important; padding-bottom: 0px !important; padding-top: 0px !important; " />*@
            </div>
            <div class="modal-body" id="partial2">
                <div>
                    @Html.Partial("_Ceased")                                     
               </div>
            </div>

        </div>
    </div>
</div>

<div id="dialog" style="display: none; position:relative;">
</div>

@*<script type="text/javascript">
    $(function () {
        $('#btnReject').click(function () {
            alert(1);
            var FADID = $("#hndFADID").val();
            var FMSID = $("#hndFMSID").val();
            var status = 1;
            var route = '@Url.Action("Reject", "FixedAllowanceDetail")?FADID=' + FADID + '&FMSID=' + FMSID;
            $('#partial').load(route);
        });
    });
</script>*@

<script type="text/javascript">
    $(function () {
        $('#btnCeased').click(function () {

            var FADID = $("#hndFADID").val();
            var FMSID = $("#hndFMSID").val();
            var status = 2;
            var route = '@Url.Action("Ceased", "FixedAllowanceDetail")?FADID=' + FADID + '&FMSID=' + FMSID + '&FID=' + status;
         

            $('#partial2').load(route);

        });
    });
</script>

<script type="text/javascript">

    $(function () {
        //Evoid Conflict of the two version jqery
        //$.noConflict();
        $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            title: "User Flow History...", height: 350, width: 800
        });

        $("#details").click(function () {
            var FADID = $("#hndFADID").val();
            $.ajax({
                type: "POST",
                url: '@Url.Content("~/FixedAllowanceDetail/UserFlowHistory")',
                data: '{FADID:"'+ FADID +'" }',
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (response) {
                    $('#dialog').html(response);
                    $('#dialog').dialog('open');
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });

    });
</script>

PORNEW/POR/Views/FixedAllowanceDetail/Report_FAEligibleList.cshtml
@model PagedList.IPagedList<POR.Models.Vw_FAEligibleList>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
<div class="content-wrapper" style="height:900px !important;">

    <section class="content-header">
        <h1>
            Fixed Allowance Details
            <small>View Details</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
        <div id="ErrorMessage">
            @if (TempData["ScfMsg"] != null)
            {
                <div id="Msg" class="col-lg-12  alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong> @TempData["ScfMsg"]
                </div>
            }
            else if (TempData["ErrMsg"] != null)
            {
                <div id="Msg" class="col-lg-12 alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong>@TempData["ErrMsg"]
                </div>

            }
        </div>
    </section>

    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            @Html.ValidationSummary(true)

            <div class="box-body">
                @using (Html.BeginForm("Report_FAEligibleList", "FixedAllowanceDetail", FormMethod.Get))
                {
                    <div class="input-group">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                        </div>
                    </div>

                }
  
                <table id="example" class="table table-responsive table-striped table-hover">
                    <tr>                                       
                        <th>
                            @Html.ActionLink("Service No", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "ServiceNo" }, null)
                        </th>
                        <th>
                            @Html.ActionLink("Rank", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "Rank" }, null)
                        </th>
                        <th>
                            @Html.ActionLink("Name With Initials", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "Name" }, null)
                        </th>
                        <th>
                            @Html.ActionLink("Allowance Name", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "AllowanceName" }, null)
                        </th>
                        <th>
                            @Html.ActionLink("Effective Date", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "EffectiveDate" }, null)
                        </th>
                        <th>
                            @Html.ActionLink("Establishment", "Report_FAEligibleList", "FixedAllowanceDetail", new { sortOrder = "EstablishmentId" }, null)
                        </th>             
                        <th></th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {

                        <tr>                       
                            <td>
                                @Html.DisplayFor(modelItem => item.ServiceNo)
                            </td>                       
                            <td>
                                @Html.DisplayFor(modelItem => item.Rank)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AllowanceName)
                            </td>
                            <td>
                                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.EffectiveDate))
                            </td>                                          
                            <td>
                               @Html.DisplayFor(modelItem => item.PostedLocation) 
                            </td>              
                        </tr>
                    }
                </table>
                <br />
                @*Paging for Data Table *use only MVC no Javascript*@
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("Report_FAEligibleList",
                 new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </section>
</div>

@Scripts.Render("~/bundles/jquery")