PORNEW/POR/Models/F121/Cls_ItemList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace POR.Models.F121
{
    public class Cls_ItemList
    {
        public string DocName { get; set; }
        public string ServiceNo { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public int Qty { get; set; }
        public string ItemCode { get; set; }

        public string SerialNo { get; set; }
        public string FullName { get; set; }
        public string ProcName { get; set; }

    }
}

PORNEW/POR/Models/F121/_F121.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace POR.Models.F121
{
    public class _F121
    {
        public string Snumber { get; set; }
        public string ServiceNo { get; set; }
        public string SNo { get; set; }
        public string Name { get; set; }
        public string Trade { get; set; }
        public string Rank { get; set; }
        public string LocShortName { get; set; }
        public string OffencePlace { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public int OffenceID { get; set; }
        public string OffenceName { get; set; }
        public string OffenceWASO { get; set; }
        public int ChargeNo { get; set; }
        public string ChargeNo2 { get; set; }
        public Nullable<System.DateTime> OffenceDate { get; set; }
        public string Appointment { get; set; }
        public int PunishmentID { get; set; }

        public string Punishment { get; set; }
        public int Sec40 { get; set; }

        public int OptCM { get; set; }
        public int RecCM { get; set; }
        public string PunishmentDescription { get; set; }
        public Nullable<System.DateTime> PunishDate { get; set; }
        public Nullable<int> FMSID { get; set; }
        public Nullable<int> RSID { get; set; }
        public int CHID { get; set; }

        public string Comment { get; set; }

        public DateTime? fromDate { get; set; }

        public DateTime? toDate { get; set; }

    }
}

PORNEW/POR/Controllers/F121Controller.cs
using System.Linq;
using System.Web.Mvc;
using System.Data;
using POR.Models;
using System;
using POR.Models.F121;
using System.Transactions;
using System.Collections.Generic;
using PagedList;

namespace POR.Controllers
{
    public class F121Controller : Controller
    {
        dbContext _db = new dbContext();
        dbContextCommonData _dbCommonData = new dbContextCommonData();
        List<Cls_ItemList> lst_ListPartItem = new List<Cls_ItemList>();
        List<Cls_ItemList> lst_ListItem = new List<Cls_ItemList>();
        // GET: F121
        [HttpGet]
        public ActionResult Create()
        {
            ///Create By: Fg Off RGSD GAMAGE
            ///Create Date: 01/01/2022  
            ///Description: por clerk initial step stage of crate F121 Charge cheet

            try
            {

                ViewBag.DDL_Establishment = new SelectList(_dbCommonData.Establishments, "LocShortName", "LocShortName");
                ViewBag.DDL_OffenceName = new SelectList(_db.Vw_Offences.OrderBy(x => x.OffenceName), "OffenceID", "OffenceName");
                ViewBag.DDL_Punishments = new SelectList(_db.Vw_Punishments.OrderBy(x => x.Punishment), "PunishmentID", "Punishment");


                //List<SelectListItem> Sec40 = new List<SelectListItem>();

                //Sec40.Add(new SelectListItem { Text = "Yes", Value = "1" });
                //Sec40.Add(new SelectListItem { Text = "No", Value = "2" });
                //ViewBag.Sec40 = Sec40;

                //List<SelectListItem> OptCM = new List<SelectListItem>();

                //OptCM.Add(new SelectListItem { Text = "Yes", Value = "3" });
                //OptCM.Add(new SelectListItem { Text = "No", Value = "4" });
                //ViewBag.OptCM = OptCM;


                //List<SelectListItem> RecCM = new List<SelectListItem>();

                //RecCM.Add(new SelectListItem { Text = "Yes", Value = "5" });
                //RecCM.Add(new SelectListItem { Text = "No", Value = "6" });
                //ViewBag.RecCM = RecCM;

            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View();
        }






        [HttpPost]
        public ActionResult Create(_F121 _objF252ChargeHeader)
        {

            ///Create By: Fg Off RGSD GAMAGE
            ///Create Date: 01/01/2022  
            ///Description: por clerk initial step stage of crate F121 Charge cheet data save to DB 


            F252ChargeHeader objF252ChargeHeader = new F252ChargeHeader();
            F252WitnessHeader objF252WitnessHeader = new F252WitnessHeader();
            F252WittnessPerson objF252WittnessPerson = new F252WittnessPerson();
            F252OffenceInfo objF252OffenceInfo = new F252OffenceInfo();
            WitnessDocument ObjWitnessDocument = new WitnessDocument();
            F252PunishmentHeader objF252PunishmentHeader = new F252PunishmentHeader();
            F252PunishmentDetails objF252PunishmentDetails = new F252PunishmentDetails();

            //Get the MAC Address of the User PC
            string MacAddress = new DALBase().GetMacAddress();
            string message = "";
            int UID_ = 0;
            int RoleId = 0;

            lst_ListItem = (List<Cls_ItemList>)Session["ListItem"];
            lst_ListPartItem = (List<Cls_ItemList>)Session["lst_ListPartItem"];


            if (Session["UID"] != null)
            {


                try
                {
                    if (_objF252ChargeHeader.ChargeDate != null && _objF252ChargeHeader.OptCM != 0 && _objF252ChargeHeader.RecCM != 0 &&
                    _objF252ChargeHeader.Sec40 != 0 && _objF252ChargeHeader.OffenceWASO != null && _objF252ChargeHeader.LocShortName != null &&
                    _objF252ChargeHeader.OffenceDate != null && _objF252ChargeHeader.PunishDate != null && _objF252ChargeHeader.PunishmentID != 0 &&
                    _objF252ChargeHeader.Appointment != null && _objF252ChargeHeader.PunishmentDescription != null && lst_ListItem.Count != 0 && lst_ListPartItem.Count != 0)
                    {
                        UID_ = Convert.ToInt32(Session["UID"]);

                        ViewBag.DDL_Establishment = new SelectList(_dbCommonData.Establishments, "LocShortName", "LocShortName");
                        ViewBag.DDL_OffenceName = new SelectList(_db.Vw_Offences.OrderBy(x=>x.OffenceName), "OffenceID", "OffenceName");
                        
                        ViewBag.DDL_Punishments = new SelectList(_db.Vw_Punishments.OrderBy(x => x.Punishment), "PunishmentID", "Punishment");

                        RoleId = _db.UserInfoes.Where(x => x.UID == UID_ && x.Active == 1).Select(x => x.RoleId).FirstOrDefault();
                        var LocationId = _db.UserInfoes.Where(x => x.UID == UID_).Select(x => x.LocationId).FirstOrDefault();
                        /// Get the service type related to service number.
                        var ServiceType = _db.Vw_PersonalDetail.Where(x => x.SNo == _objF252ChargeHeader.Snumber).Select(x => x.service_type).FirstOrDefault();

                        /////


                        ////







                        if (ModelState.IsValid)
                        {
                            objF252ChargeHeader.ChargeNo = _objF252ChargeHeader.ChargeNo;
                            objF252ChargeHeader.ChargeNo2 = _objF252ChargeHeader.ChargeNo2;
                            objF252ChargeHeader.ChargeDate = _objF252ChargeHeader.ChargeDate;
                            objF252ChargeHeader.CreateLocation = LocationId;
                            objF252ChargeHeader.Sno = _objF252ChargeHeader.Snumber;
                            objF252ChargeHeader.ServiceTypeId = ServiceType;
                            objF252ChargeHeader.IsOptedCM = _objF252ChargeHeader.OptCM;
                            objF252ChargeHeader.IsRemanForCM = _objF252ChargeHeader.RecCM;
                            objF252ChargeHeader.ISConcurrnt = 3;
                            objF252ChargeHeader.IsSec40Compiled = _objF252ChargeHeader.Sec40;
                            objF252ChargeHeader.CreatedBy = UID_;
                            objF252ChargeHeader.CreatedDate = DateTime.Now;
                            objF252ChargeHeader.CreatedMac = MacAddress;
                            objF252ChargeHeader.CreatedIP = this.Request.UserHostAddress;
                            objF252ChargeHeader.Active = 1;
                            _db.F252ChargeHeader.Add(objF252ChargeHeader);

                            using (TransactionScope scope = new TransactionScope(TransactionScopeOption.RequiresNew))
                            {
                                if (_db.SaveChanges() > 0)
                                {
                                    var CHID = _db.F252ChargeHeader.Where(x => x.ChargeNo == (_objF252ChargeHeader.ChargeNo)
                                                 && x.Sno == _objF252ChargeHeader.Snumber && x.Active == 1).OrderByDescending(x => x.CreatedDate)
                                                 .Select(x => x.CHID).FirstOrDefault();



                                    /// This function is to  Enter intial record Status in to FlowStatusDetails 
                                    InserFlowStatus(CHID, RoleId, UID_, _objF252ChargeHeader.FMSID, _objF252ChargeHeader.RSID);
                                    //string Location = Convert.ToString(_objF252ChargeHeader.LocShortName);

                                    objF252OffenceInfo.OffenceTypeId = _objF252ChargeHeader.OffenceID;
                                    objF252OffenceInfo.CHID = CHID;
                                    objF252OffenceInfo.OffenceWASO = _objF252ChargeHeader.OffenceWASO;
                                    objF252OffenceInfo.OffencePlace = _objF252ChargeHeader.LocShortName.Trim();
                                    objF252OffenceInfo.OffenceDate = _objF252ChargeHeader.OffenceDate;
                                    objF252OffenceInfo.CreatedBy = UID_;
                                    objF252OffenceInfo.CreatedDate = DateTime.Now;
                                    objF252OffenceInfo.CreatedMac = MacAddress;
                                    objF252OffenceInfo.CreatedIP = Request.UserHostAddress;
                                    objF252OffenceInfo.Active = 1;
                                    _db.F252OffenceInfo.Add(objF252OffenceInfo);

                                    //InsertFlowStatus(_objF252ChargeHeader, CHID);
                                    objF252PunishmentHeader.PunishDate = _objF252ChargeHeader.PunishDate;
                                    objF252PunishmentHeader.PunishmentID = _objF252ChargeHeader.PunishmentID;
                                    objF252PunishmentHeader.Appointment = _objF252ChargeHeader.Appointment;
                                    objF252PunishmentHeader.CHID = CHID;
                                    objF252PunishmentHeader.CreatedBy = UID_;
                                    objF252PunishmentHeader.CreatedDate = DateTime.Now;
                                    objF252PunishmentHeader.CreatedMac = MacAddress;
                                    objF252PunishmentHeader.CreatedIP = Request.UserHostAddress;
                                    objF252PunishmentHeader.Active = 1;
                                    _db.F252PunishmentHeader.Add(objF252PunishmentHeader);


                                    objF252WitnessHeader.CHID = CHID;
                                    objF252WitnessHeader.CreatedBy = UID_;
                                    objF252WitnessHeader.CreatedDate = DateTime.Now;
                                    objF252WitnessHeader.CreatedMac = MacAddress;
                                    objF252WitnessHeader.CreatedIP = Request.UserHostAddress;
                                    objF252WitnessHeader.Active = 1;
                                    _db.F252WitnessHeader.Add(objF252WitnessHeader);

PORNEW/POR/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POR.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/
        public ActionResult Index(string Month, string Year)
        {
            if (Month != null || Year != null)
            {
                return Redirect("~/Report/FixedAllowanceReport.aspx?Month=" + Month + "&Year=" + Year + "");
            }
            else
            {
                return View();
            }

        }
	}
}

PORNEW/POR/Views/F121/IndexConfirmF121.cshtml
@model PagedList.IPagedList<POR.Models.F121._F121>
@using PagedList.Mvc;
@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/adminlte/css/AdminLTE.css" rel="stylesheet" />
<div class="content-wrapper" style="height:900px !important;">

    <section class="content-header">
        <h1>
            F121 Forward List
            <small>F121 Your list</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">F121 Forward List</li>
        </ol>
        <div id="ErrorMessage">
            @if (TempData["ScfMsg"] != null)
            {
                <div id="Msg" class="col-lg-12  alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong> @TempData["ScfMsg"]
                </div>
            }
            else if (TempData["ErrMsg"] != null)
            {
                <div id="Msg" class="col-lg-12 alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong>@TempData["ErrMsg"]
                </div>

            }
        </div>
    </section>

    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            @Html.ValidationSummary(true)

            <div class="box-body">
                @using (Html.BeginForm("IndexConfirmF121", "F121", FormMethod.Get))
                {
                    <div class="input-group col-lg-6">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { placeholder = "Serach using Service No", @class = "form-control" })
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                }


                <p>
                    <br />
                    <input type="button" id="forward" value="Forward" class="btn btn-primary" />
                </p>


                <table id="example" class="table table-responsive table-striped table-hover">
                    <tr>
                        <th>
                            <input type="checkbox" id="checkAll" />
                        </th>
                        <th>
                            Service No
                        </th>
                        <th>
                            Rank
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Offence Name
                        </th>
                        <th>
                            Location
                        </th>
                        <th>
                            Charge Date
                        </th>
                        <th>
                            Comment
                        </th>
                        <th>

                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                <input type="checkbox" class="checkBox" value="@item.CHID" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ServiceNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Rank)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OffenceName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OffencePlace)
                            </td>
                            <td>
                                @*@Html.DisplayFor(modelItem => item.ChargeDate)*@
                                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.ChargeDate))
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Comment)
                            </td>


                            <td>
                                @Html.ActionLink("Delete", "DeleteOIC", new { CHID = item.CHID }, new { @class = "btn btn-warning" })
                            </td>
                        </tr>
                    }

                </table>


                <br />
                @*Paging for Data Table *use only MVC no Javascript*@
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("IndexConfirmF121",
                 new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </section>
</div>
@Scripts.Render("~/bundles/jquery")

<script>


    //------------------------------All Forward

    $(document).ready(function () {

        $("#checkAll").click(function () {
            $(".checkBox").prop('checked',
                $(this).prop('checked'));
        });

        $("#forward").click(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = '../LivingInOut/Forward';
            options.type = 'POST';
            options.data = JSON.stringify(selectedIDs);
            options.contentType = 'application/json';
            options.dataType = 'json';
            options.success = function (msg) {
                location.reload();
            };
            options.error = function () {
               // alert('Error while deleting the records!');
            };
            $.ajax(options);

        });
    });

</script>

PORNEW/POR/Views/F121/IndexF121.cshtml
@model PagedList.IPagedList<POR.Models.F121._F121>
@using PagedList.Mvc;
@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/adminlte/css/AdminLTE.css" rel="stylesheet" />
<div class="content-wrapper" style="height:900px !important;">

    <section class="content-header">
        <h1>
            F121 Forward List
            <small>F121 Your list</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">F121 Forward List</li>
        </ol>
        <div id="ErrorMessage">
            @if (TempData["ScfMsg"] != null)
            {
                <div id="Msg" class="col-lg-12  alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong> @TempData["ScfMsg"]
                </div>
            }
            else if (TempData["ErrMsg"] != null)
            {
                <div id="Msg" class="col-lg-12 alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert!</strong>@TempData["ErrMsg"]
                </div>

            }
        </div>
    </section>

    <section class="col-lg-12 connectedSortable">
        <div class="nav-tabs-custom">
            @Html.ValidationSummary(true)

            <div class="box-body">
                @using (Html.BeginForm("IndexF121", "F121", FormMethod.Get))
                {
                    <div class="input-group col-lg-6">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { placeholder = "Serach using Service No", @class = "form-control" })
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                }


                <p>
                    <br />
                    <input type="button" id="forward" value="Forward" class="btn btn-primary" />
                </p>


                <table id="example" class="table table-responsive table-striped table-hover">
                    <tr>
                        <th>
                            <input type="checkbox" id="checkAll" />
                        </th>
                        <th>
                            Service No
                        </th>
                        <th>
                            Rank
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Offence Name
                        </th>
                        <th>
                            Location
                        </th>
                        <th>
                            Charge Date
                        </th>
                        <th>

                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                <input type="checkbox" class="checkBox" value="@item.CHID" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ServiceNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Rank)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OffenceName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OffencePlace)
                            </td>
                            <td>
                                @*@Html.DisplayFor(modelItem => item.ChargeDate)*@
                                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.ChargeDate))
                            </td>


                            <td>
                                @Html.ActionLink("Details", "Details", new { CHID = item.CHID }, new { @class = "btn btn-primary" })
                            </td>

                            <td>
                                @Html.ActionLink("Delete", "Delete", new { CHID = item.CHID }, new { @class = "btn btn-warning" })
                            </td>
                        </tr>
                    }


                </table>


                <br />
                @*Paging for Data Table *use only MVC no Javascript*@
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("IndexF121",
                 new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </section>
</div>
@Scripts.Render("~/bundles/jquery")

<script>


    //------------------------------All Forward

    $(document).ready(function () {

        $("#checkAll").click(function () {
            $(".checkBox").prop('checked',
                $(this).prop('checked'));
        });

        $("#forward").click(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = '../LivingInOut/Forward';
            options.type = 'POST';
            options.data = JSON.stringify(selectedIDs);
            options.contentType = 'application/json';
            options.dataType = 'json';
            options.success = function (msg) {
                location.reload();
            };
            options.error = function () {
               // alert('Error while deleting the records!');
            };
            $.ajax(options);

        });
    });

</script>

PORNEW/POR/Views/F121/Report.cshtml
@{
    ViewBag.Title = "SalesSummery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using POR.Models.F121;
@model POR.Models.F121._F121

<section id="about"></section>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Invoice Details
        </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container">
            @using (Html.BeginForm("Report", "F121", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-3">
                        <div class="input-group">
                            <div class="form-group" style="width:290px;">
                                <label>From Date</label>
                                <div class="input-group date" style="width:290px;">
                                    @Html.TextBoxFor(m => m.fromDate, new { @id = "datepicker", @placeholder = "Enter From Date", @class = "form-control", @required = "required", title = "Enter From Date", @style = "width:250px" })
                                    <div class="input-group-addon" id="datetime">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="input-group">
                            <div class="form-group" style="width:290px;">
                                <label>To Date</label>
                                <div class="input-group date" style="width:290px;">
                                    @Html.TextBoxFor(m => m.toDate, new { @id = "Todatepicker", @placeholder = "Enter To Date", @class = "form-control", @required = "required", title = "Enter To Date", @style = "width:250px" })
                                    <div class="input-group-addon" id="datetime">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group fa-align-right">
                            <input type="submit" class="btn btn-lg btn-primary btn-block" style="width:100px" value="View" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-1">
                        <iframe src="~/Report/RDLC/F121_Monlthy_Report.aspx" width="1000" height="568"></iframe>
                    </div>
                </div>
            }

        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {

      $('#example1').DataTable()
      $('#example21').DataTable({
          'paging': true,
          'lengthChange': true,
          'searching': true,
          'ordering': true,
          'info': true,
          'autoWidth': true
      })

      //$(function () {
      //    $('#datepicker').Da
      //});
        //Datemask dd/mm/yyyy
      $('#inputmask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd-mm-yyyy' })
        //Datemask2 mm/dd/yyyy
      $('#inputmask').inputmask('mm/dd/yyyy', { 'placeholder': 'mm-dd-yyyy' })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A' })
        //Date range as a button
        $('#daterange-btn').daterangepicker(
          {
            ranges   : {
              'Today'       : [moment(), moment()],
              'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
              'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
              'Last 30 Days': [moment().subtract(29, 'days'), moment()],
              'This Month'  : [moment().startOf('month'), moment().endOf('month')],
              'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate  : moment()
          },
          function (start, end) {
            $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
          }
        )

        //Date picker
        $('#datepicker').datepicker({
          autoclose: true
        })
      //Date picker
        $('#Todatepicker').datepicker({
            autoclose: true
        })
        //$(function () {
        //    $('#datepicker').datetimepicker();
        //});

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        })
        //Red color scheme for iCheck
        $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
          checkboxClass: 'icheckbox_minimal-red',
          radioClass   : 'iradio_minimal-red'
        })
        //Flat red color scheme for iCheck
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
          checkboxClass: 'icheckbox_flat-green',
          radioClass   : 'iradio_flat-green'
        })

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        //Timepicker
        $('.timepicker').timepicker({
          showInputs: true
        })
      })
    </script>
}