PORNEW/POR/Models/PersonalContact/_PsnContactHeader.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace POR.Models.PersonalContact
{
    public class _PsnContactHeader
    {
        public int PCHID { get; set; }
        public int FSPCID { get; set; }
        public string ServiceNo { get; set; }
        public int ServiceType { get; set; }
        public string Rank { get; set; }
        public string FullName { get; set; }
        public string Trade { get; set; }
        public string Remarks { get; set; }
        public string RefNo { get; set; }
        public string Location { get; set; }
        public int RSID { get; set; }
        [Required(ErrorMessage = "Please Select the Por Category")]
        public int MasSubCatID { get; set; }
        public string SubCatName { get; set; }
        [Required(ErrorMessage = "Authority filed is Required.")]
        public string Authority { get; set; }
        public int PreviousReject { get; set; }
        public string RejectAuth { get; set; }
        public int ISProcessed { get; set; }
        public string Comment { get; set; }
        public string RejectRoleName { get; set; }
        public string UserRoleName { get; set; }
        
        public string RejectRefNo { get; set; }
        public int CurrentUserRole { get; set; }

        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Please enter a valid 10-digit mobile number.")]
        public string MobileNo { get; set; }
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Please enter a valid 10-digit mobile number.")]
        
        public string ResidentialTeleNo { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string EmailAddress { get; set; }
        /// <summary>
        ///  Child Details
        /// </summary>

        public Nullable<int> PCDID { get; set; }
        public string ChildFullName { get; set; }
        public string ChildFullNameWithInitial { get; set; }
        public string Disrict2 { get; set; }
        public string Disrict3 { get; set; }
        public string BirthPlace { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int>  District { get; set; }
        public string GenderType { get; set; }
        public string BirthCertificateNo { get; set; }
        public string DeathCertificateNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<int> SCID { get; set; }
        public Nullable<int> FMSID { get; set; }
        public DateTime ProcessedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedMac { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedMac { get; set; }
        public Nullable<int> Active { get; set; }
        public string CreateIpAddess { get; set; }
    }
}

PORNEW/POR/Controllers/PersonalContactController.cs
using Microsoft.Reporting.WebForms;
using PagedList;
using POR.Models;
using POR.Models.PersonalContact;
using ReportData.BAL;
using ReportData.DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace POR.Controllers
{
    public class PersonalContactController : Controller
    {
        
        DALCommanQuery objDALCommanQuery = new DALCommanQuery();
        DALCommanQueryP2 objDALCommanQueryP2 = new DALCommanQueryP2();
        dbContextCommonData _dbCommonData = new dbContextCommonData();
        dbContext _db = new dbContext();
        P3HRMS _dbP3HRMS = new P3HRMS();


        string MacAddress = new DALBase().GetMacAddress();
        int UID = 0;
        
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? RSID)
        {
            ///Created BY   : Sqn ldr WAKY Wickramasinghe
            ///Created Date : 2023/04/28
            /// Description : Index Page for Forward Load Person Contact Details            

            DataTable dt = new DataTable();
            DataTable dt2 = new DataTable();
            DataTable dt3 = new DataTable();
            int serviceStatus = 0;

            List<_PsnContactHeader> PsnContactList = new List<_PsnContactHeader>();

            int? UID = Convert.ToInt32(Session["UID"]);
            int pageSize = 0;
            int pageNumber = 1;

            var UserInfo = _db.UserInfoes.Where(x => x.UID == UID).Select(x => new { x.LocationId, x.DivisionId, x.RoleId ,x.UserRoleCategory}).FirstOrDefault();
            var LocationId = _db.UserInfoes.Where(x => x.UID == UID).Select(x => new { x.LocationId, x.DivisionId, x.RoleId }).FirstOrDefault();
            string UserDivisionId = _db.UserInfoes.Where(x => x.UID == UID).Select(x => x.DivisionId).FirstOrDefault();

            if (UserInfo.UserRoleCategory == "P2")
            {
                serviceStatus = 1;
            }
            else
            {
                serviceStatus = 2;
            }

            if (UID != 0)
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Ref_No" : "";
                ViewBag.CurrentFilter = searchString;
                int RoleId = UserInfo.RoleId;
                TempData["CurrentUserRole"] = RoleId;
                long sno = 0;

                if (!string.IsNullOrEmpty(searchString))
                {
                    page = 1;

                    var Sno = _db.Vw_PersonalDetail.Where(x => x.ServiceNo == searchString).Select(x => x.SNo).FirstOrDefault();
                    sno = Convert.ToInt64(Sno);

                    ViewBag.CurrentFilter = searchString;
                }
                else
                {
                    searchString = currentFilter;
                    ViewBag.CurrentFilter = searchString;

                }

                ReportData.DAL.DALCommanQuery objDALCommanQuery = new ReportData.DAL.DALCommanQuery();

                dt = objDALCommanQuery.CallPersonalContatSP(sno);

                var resultStatus = dt.AsEnumerable().Where(x => x.Field<int>("Active") == 1 && x.Field<int>("RecordStatusID") == (int)POR.Enum.RecordStatus.Forward || x.Field<int>("RecordStatusID") == (int)POR.Enum.RecordStatus.Insert).ToList();

                if (resultStatus.Count != 0)
                {
                    dt2 = dt.AsEnumerable().Where(x => x.Field<int>("Active") == 1 && x.Field<int>("RecordStatusID") == (int)POR.Enum.RecordStatus.Forward || x.Field<int>("RecordStatusID") == (int)POR.Enum.RecordStatus.Insert).CopyToDataTable();
                }
                switch (UserInfo.RoleId)
                {
                    case (int)POR.Enum.UserRole.P3CLERK:
                    case (int)POR.Enum.UserRole.P2CLERK:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.P3SNCO:
                    case (int)POR.Enum.UserRole.P2SNCO:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.P3OIC:
                    case (int)POR.Enum.UserRole.P2OIC:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.KOPNR:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.SNCOSALARY:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.WOSALARY:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.HRMSCLKP3VOL:
                    case (int)POR.Enum.UserRole.HRMSCLKP2VOL:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.HRMSSNCO:
                    case (int)POR.Enum.UserRole.HRMSP2SNCO:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.ASORSOVRP3VOL:
                    case (int)POR.Enum.UserRole.ASORSOVRP2VOL:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    case (int)POR.Enum.UserRole.ACCOUNTS01:
                        dt3 = loadDataUserWise(RoleId, dt2, UserInfo.LocationId, UID, serviceStatus);
                        break;
                    default:
                        break;
                }

                for (int i = 0; i < dt3.Rows.Count; i++)
                {
                    _PsnContactHeader obj_PsnContactHeader = new _PsnContactHeader();
                    obj_PsnContactHeader.PCHID = Convert.ToInt32(dt3.Rows[i]["PCHID"]);
                    obj_PsnContactHeader.ServiceNo = dt3.Rows[i]["ServiceNo"].ToString();
                    obj_PsnContactHeader.Rank = dt3.Rows[i]["Rank"].ToString();
                    obj_PsnContactHeader.FullName = dt3.Rows[i]["Name"].ToString();
                    obj_PsnContactHeader.Location = dt3.Rows[i]["Location"].ToString();                   
                    obj_PsnContactHeader.RefNo = dt3.Rows[i]["RefNo"].ToString();
                    obj_PsnContactHeader.SubCatName = dt3.Rows[i]["SubCatName"].ToString();
                    obj_PsnContactHeader.CurrentUserRole = Convert.ToInt32(dt3.Rows[i]["CurrentStatus"]);
                    PsnContactList.Add(obj_PsnContactHeader);

                }
                pageSize = 20;
                pageNumber = (page ?? 1);
                return View(PsnContactList.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
            
        }
        public ActionResult IndexChildInfo(string sortOrder, string currentFilter, string searchString, int? page, int? RSID)
        {
            ///Created BY   : Sqn ldr WAKY Wickramasinghe
            ///Created Date : 2023/04/28
            ///Description : Load Childern details

            ///This serviceStatus assign form the when click the side navigation of the respective menu. 
            /// serviceStatus = 1 officer and serviceStatus = 2 Other rank, this serviceStatus is to get officer and other rank details seperetly

            DataTable dt = new DataTable();
            DataTable dt2 = new DataTable();
            DataTable dt3 = new DataTable();

            List<_PsnContactHeader> PsnContactList = new List<_PsnContactHeader>();

            int? UID = Convert.ToInt32(Session["UID"]);
            int pageSize = 0;
            int pageNumber = 1;
            int serviceStatus = 0;

            var UserInfo = _db.UserInfoes.Where(x => x.UID == UID).Select(x => new { x.LocationId, x.DivisionId, x.RoleId, x.UserRoleCategory }).FirstOrDefault();
            var LocationId = _db.UserInfoes.Where(x => x.UID == UID).Select(x => new { x.LocationId, x.DivisionId, x.RoleId }).FirstOrDefault();
            string UserDivisionId = _db.UserInfoes.Where(x => x.UID == UID).Select(x => x.DivisionId).FirstOrDefault();

            if (UserInfo.UserRoleCategory == "P2")
            {
                serviceStatus = 1;
            }
            else
            {
                serviceStatus = 2;
            }

            if (UID != 0)
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Ref_No" : "";
                ViewBag.CurrentFilter = searchString;
                int RoleId = UserInfo.RoleId;
                TempData["CurrentUserRole"] = RoleId;
                long sno = 0;
                int PsnConHeaderID = 0;

                if (!string.IsNullOrEmpty(searchString))
                {
                    page = 1;

                    var Sno = _db.Vw_PersonalDetail.Where(x => x.ServiceNo == searchString).Select(x => x.SNo).FirstOrDefault();
                    sno = Convert.ToInt64(Sno);

                    ViewBag.CurrentFilter = searchString;
                }
                else
                {
                    searchString = currentFilter;
                    ViewBag.CurrentFilter = searchString;

                }

                ReportData.DAL.DALCommanQuery objDALCommanQuery = new ReportData.DAL.DALCommanQuery();

PORNEW/POR/Views/PersonalContact/AdvancedSearchPsnCon.cshtml
@model PagedList.IPagedList<POR.Models.PersonalContact._PsnContactHeader>
@using PagedList.Mvc;

<link href="~/Content/CustomStyle.css" rel="stylesheet" />
<script src="~/Scripts/Jq.js"></script>
<div class="content-wrapper">
    <section class="content-header">

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">
                Advanced Searching for Personal Contact Details
            </li>
        </ol>
        <div id="ErrorMessage">
            @if (TempData["ScfMsg"] != null)
            {
                <div id="Msg" class="col-lg-12  alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert! </strong> @TempData["ScfMsg"]
                </div>
            }
            else if (TempData["ErrMsg"] != null)
            {
                <div id="Msg" class="col-lg-12 alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Alert! </strong>@TempData["ErrMsg"]
                </div>
            }
        </div>

        <br />
    </section>

    <section class="col-lg-12 connectedSortable">
        <h3>
            Advanced Search - Personal Contact Details
        </h3>
        <div class="nav-tabs-custom">
            @Html.ValidationSummary(true)
            <div class="box-body">
                @using (Html.BeginForm("AdvancedSearchPsnCon", "PersonalContact", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.Label("From Date", new { @class = "control-label" })
                                <input id="searchDate" type="date" name="FromDate" class="form-control" />
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.Label("To Date", new { @class = "control-label" })
                                <input id="searchDate" type="date" name="ToDate" class="form-control" />
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                @Html.Label("Select Location", new { @class = "control-label" })
                                @Html.DropDownList("SearchLoc", ViewBag.DDL_Location as SelectList, "SELECT", htmlAttributes: new { @id = "dpPorLoc", @class = "form-control" })
                            </div>
                        </div>

                        <div class="col-lg-3">
                            <div class="form-group">
                                @Html.Label("POR Sub Category", new { @class = "control-label" })
                                @Html.DropDownList("SearchLivingStatus", ViewBag.DDL_PersonalContactCat as SelectList, "SELECT", htmlAttributes: new { @id = "dpPorSubCat", @class = "form-control" })

                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                @Html.Label("Select Record Status", new { @class = "control-label" })
                            </div>
                            <div style="font-weight:bold">
                                Forward : @Html.RadioButton("RecordStatus", "2000", new { @class = "form-check-input", @id = "ForwardRb" })
                                Reject  : @Html.RadioButton("RecordStatus", "3000", new { @class = "form-check-input", @id = "RejectRb" })
                            </div>
                        </div>
                        <div class="col-lg-3" style="margin-top:25px">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-success"><i class="fa fa-search">&emsp;Search</i></button>
                                </div>
                                <div class="input-group-btn">
                                    <button type="button" id="btnClear" class="btn btn-warning"><i class="fa fa-trash">&emsp;Clear</i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <section>

                    <table id="example" class="table table-responsive table-striped table-hover">

                        <tr>
                            <th>
                               Service No
                            </th>
                            <th>
                               Rank
                            </th>
                            <th>
                                Name With Initials
                            </th>
                            <th>
                                Location
                            </th>
                            <th>
                                Reference No
                            </th>
                            <th>
                                Category Name
                            </th>
                            <th>
                                Current Status
                            </th>
                            <th></th>
                            <th></th>
                        </tr>

                        @{
                            if (Model != null)
                            {
                                int recordCount = Convert.ToInt32(TempData["recordCount"]);
                                <caption><h4>Total Record Count : @recordCount</h4></caption>
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.ServiceNo)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.Rank)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.FullName)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.Location)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.RefNo)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.SubCatName)
                                        </td>
                                        <td style="width:300px">
                                            @Html.DisplayFor(modelItem => item.UserRoleName)
                                        </td>                                       
                                    </tr>
                                }
                            }
                        }

                    </table>

                    @if (Model != null)
                    {
                        //Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("AdvancedSearchPsnCon",
                            new
                            {
                                page,
                                sortOrder = ViewBag.CurrentSort,
                                currentFilterFDate = ViewBag.currentFilterFDate,
                                currentFilterTDate = ViewBag.currentFilterTDate,
                                currentFilterLocation = ViewBag.currentFilterLocation,
                                currentFilterCategory = ViewBag.currentFilterCategory,
                                currentFilterRecStatus = ViewBag.currentFilterRecStatus

                            }))

                    }

                </section>

            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    
    $(function () {
        $("#btnClear").bind("click", function () {
            $("#dpPorSubCat")[0].selectedIndex = 0;
            $("#dpPorLoc")[0].selectedIndex = 0;
            $("#ForwardRb").removeAttr("checked");
            $("#RejectRb").removeAttr("checked");

        });

    });
</script>

PORNEW/POR/Views/PersonalContact/Edit.cshtml
@model POR.Models.PersonalContact._PsnContactHeader


<script src="~/Scripts/Jq.js"></script>
@*<script src="~/Scripts/LivingInOut.js"></script>*@
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-wrapper">
        <section class="content-header">

            <h1 style="text-align:center"><span>Edit Personal Contact Details</span></h1>

            <div id="ErrorMessage">
                @if (TempData["ScfMsg"] != null)
                {
                    <div id="Msg" class="col-lg-12  alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>Alert! </strong> @TempData["ScfMsg"]
                    </div>
                }
                else if (TempData["ErrMsg"] != null)
                {
                    <div id="Msg" class="col-lg-12 alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>Alert! </strong>@TempData["ErrMsg"]
                    </div>
                }
            </div>
        </section>
        <br />
        @{
            int RejectStatus = Convert.ToInt32(TempData["Rejectstatus"]);
            int MasSubCatId = Convert.ToInt32(TempData["massSubId"]);
            <section class="col-lg-6 connectedSortable">
                <div class="nav-tabs-custom">
                    @Html.ValidationSummary(true)

                    <div class="box-body">
                        @*Service Number /Rank*@
                        <div class="form-group">
                            <div class="col-lg-6">
                                @Html.Label("Service Number", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.ServiceNo, new { @class = "form-control ", autocomplete = "off", @readonly = "readonly" })
                                @Html.HiddenFor(model => model.PCHID, new { @class = "form-control ", autocomplete = "off" })  
                                @Html.HiddenFor(model => model.MasSubCatID, new { @class = "form-control ", autocomplete = "off" })                              
                            </div>
                            @*Rank*@
                            <div class="col-lg-6">
                                @Html.Label("Rank", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Rank, new { @class = "form-control ", autocomplete = "off", placeholder = "", @readonly = "readonly" })
                            </div>

                        </div>

                        @*Name*@
                        <div class="form-group">
                            <div class="col-lg-12" style="margin-top:12px">
                                @Html.Label("Name", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.FullName, new { @class = "form-control ", autocomplete = "off", placeholder = "", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.FullName, string.Empty, new { @class = "label label-danger" })
                            </div>
                        </div>

                        @*Location/Authority*@
                        <div class="form-group">
                            <div class="col-lg-6" style="margin-top:12px">
                                @Html.Label("Location", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Location, new { @class = "form-control ", autocomplete = "off", placeholder = "" , @readonly = "readonly" })                               
                            </div>
                            <div class="col-lg-6" style="margin-top:12px">
                                @Html.Label("Authority", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.Authority, new { @class = "form-control ", autocomplete = "off", placeholder = "" })                               
                            </div>                            
                        </div>

                        @*POR RefNo*@
                        <div class="form-group">
                            <div class="col-lg-12" style="margin-top:12px">
                                @Html.Label("Ref No", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.RefNo, new { @class = "form-control ", autocomplete = "off", placeholder = "", @readonly = "readonly" })                               
                            </div>
                        </div>

                        @*RejectStatus == 2 mean it's reject Record*@

                        @if (RejectStatus == 2)
                        {
                            <div class="form-group">
                                @Html.Label("Reject Ref No", new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.RejectRefNo, new { @class = "form-control alert-danger", autocomplete = "off", @readonly = "readonly" })
                            </div>
                        }

                        @{
                            switch (MasSubCatId)
                            {
                                case (int)POR.Enum.PORMasterSubCategory.MobileNo:
                                    @* Mobile No :*@
                                    <div class="form-group">
                                        <div class="col-lg-12" style="margin-top:12px">
                                            @Html.Label("Mobile No", new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control ", autocomplete = "off", placeholder = "" })
                                        </div>
                                    </div>                                             
                                    break;
                                case (int)POR.Enum.PORMasterSubCategory.ResidentialTeleNo:
                                    @* ResidentialTeleNo :*@
                                    <div class="form-group">
                                        <div class="col-lg-12" style="margin-top:12px">
                                            @Html.Label(" Residential Tele No", new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.ResidentialTeleNo, new { @class = "form-control ", autocomplete = "off", placeholder = "" })
                                        </div>
                                    </div>                                   
                                    break;

                                case (int)POR.Enum.PORMasterSubCategory.EMailAddress:               

                                   @* Email Address :*@
                                    <div class="form-group">
                                        <div class="col-lg-12" style="margin-top:12px">
                                            @Html.Label("Email Address", new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.EmailAddress, new { @class = "form-control ", autocomplete = "off", placeholder = ""})
                                        </div>
                                    </div>
                                    break;

                                default:
                                    break;
                            }
                         }                      
                        <div class="form-group">
                            <section class="col-lg-6" style="margin-top:20px">
                                <button type="button" class="col-lg-4 btn btn-warning pull-right" id="btnYes" style="height:40px;width:200px" onclick="location.href='@Url.Action("Index", "PersonalContact", new { serviceStatus = 0})'">
                                    <span class="info-box-text"><i class=" fa fa-hand-o-left"></i> Go to Pending List</span>
                                </button>
                            </section>

                            <section class="col-lg-6" style="margin-top:20px">
                                <button type="submit" class="col-lg-4 btn btn-success pull-right" style="height:40px;width:200px">
                                    <span class="info-box-text"><i class=" fa fa-save"></i> Save</span>
                                </button>
                                @*<i class=" fa fa-hand-o-left"><input type="submit" value="Save" class="btn btn-success pull-right submitBtn"></i>*@
                            </section>
                        </div>
                    </div>
                </div>
            </section>            
        }
    </div>
}
<script>

</script>